name: Publish Docker image
on:
  # 当对分支main进行push操作的时候，这个工作流就被触发了
#   push:
#     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yangyang202107/aliyun_flask_ddns:latest
      
    - name: Docker Push
      run: docker push yangyang202107/aliyun_flask_ddns
